package:
  name: seqlog
  version: '0.4.2'

requirements:
  host:
    - python
    - setuptools

  run:
    - python

source:
  git_url: http://github.com/tintoy/seqlog.git

about:
  home: http://github.com/tintoy/seqlog
  license: MIT
  license_file: LICENSE
